#!/bin/bash

psql -U ${POSTGRES_USER} <<-END
    CREATE USER ${DB_ANON_ROLE};
    GRANT USAGE ON SCHEMA ${DB_SCHEMA} TO ${DB_ANON_ROLE};
    ALTER DEFAULT PRIVILEGES IN SCHEMA ${DB_SCHEMA} GRANT ALL ON TABLES TO ${DB_ANON_ROLE};
    GRANT ALL ON ALL SEQUENCES IN SCHEMA ${DB_SCHEMA} TO ${DB_ANON_ROLE};

    -- tables and views:
    GRANT ALL ON ALL TABLES IN SCHEMA ${DB_SCHEMA} TO ${DB_ANON_ROLE};

    GRANT ALL ON ALL FUNCTIONS IN SCHEMA ${DB_SCHEMA} TO ${DB_ANON_ROLE};

END
